main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('todo/', views.index, name='index'),
    path("<int:id>", views.list_created, name="list_created"),
    path('create/', views.create, name='create'),
    path("view/", views.view, name="view"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from register import views as v

urlpatterns = [
    path('', views.home, name='todo_home'),
    path('register/', v.register, name='register'),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('django.contrib.auth.urls'))
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


class ToDoList(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='todolist', null=True)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name  # daca vrei sa arate numele in loc de object1


class Item(models.Model):
    todolist = models.ForeignKey(ToDoList, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    complete = models.BooleanField()

    def __str__(self):
        return self.text

register/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms


class CreateNewList(forms.Form):
    name = forms.CharField(label='NAME', max_length=255)
    check = forms.BooleanField(required=False)

register/forms.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

main/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from .forms import CreateNewList
from . models import ToDoList
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.


@login_required(login_url='/login/')
def index(request):
    return render(request, 'main/todo.html', {})


@login_required(login_url='/login/')
def list_created(request, id):
    ls = ToDoList.objects.get(id=id)

    if ls in request.user.todolist.all():

        if request.method == "POST":
            if request.POST.get("save"):
                for item in ls.item_set.all():
                    p = request.POST

                    if "clicked" == p.get("c"+str(item.id)):
                        item.complete = True
                    else:
                        item.complete = False

                    if "text" + str(item.id) in p:
                        item.text = p.get("text" + str(item.id))

                    item.save()

            elif request.POST.get("add"):
                newItem = request.POST.get("new")
                if newItem != "":
                    ls.item_set.create(text=newItem, complete=False)
                else:
                    print("invalid")

        return render(request, "main/list_created.html", {"ls": ls})
    else:
        return render(request, "main/view.html", {})


@login_required(login_url='/login/')
def create(request):
    if request.method == "POST":
        form = CreateNewList(request.POST)

        if form.is_valid():
            n = form.cleaned_data["name"]
            t = ToDoList(name=n)
            t.save()
            request.user.todolist.add(t)

            return HttpResponseRedirect(reverse('main:list_created', args=(t.id,)))

    else:
        form = CreateNewList()
    return render(request, 'main/create.html', {'form': form})


@login_required(login_url='/login/')
def view(request):
    l = ToDoList.objects.all()
    return render(request, "main/view.html", {})

mysite/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html', {})

register/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.urls import reverse

# Create your views here.


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect(reverse('todo_home'))
    else:
        form = RegisterForm()

    return render(request, "register/register.html", {"form": form})

main/templates/main/create.html
{% extends 'base.html' %}
{% block title %}
Create
{% endblock  %}
{% block content %}
    <h3>Create a New To Do List</h3>
	<br>
	<form method="post" action={% url 'main:create' %} class="form-group">
		{% csrf_token %}
		<div class="input-group mb-3">
	  		<div class="input-group-prepend">
	  		<button name="save" type="submit" class="btn btn-success">Create</button>
	  		</div>
	  		{{form.name}}
		</div>


	</form>

{% endblock  %}

main/templates/main/list_created.html
{% extends 'base.html' %}

{% block content %}
	<h2>{{ls.name}}</h2>
	<form method="post", action="#">
		{% csrf_token %}

		{% for item in ls.item_set.all%}
			<div class="input-group mb-3">
	  			<div class="input-group-prepend">
	    			<div class="input-group-text">
	      				<input type="checkbox" name="c{{item.id}}" value="clicked" aria-label="Checkbox for following text input" {% if item.complete %} checked {% endif %}>
	    			</div>
	  			</div>
	  			<input type="text" name="text{{item.id}}" value="{{item.text}}" class="form-control" aria-label="Text input with checkbox">
			</div>
		{% endfor %}

		<div class="input-group mb-3">
	  		<div class="input-group-prepend">
	  		<button name="add", value="add", type="submit", class="btn btn-success">Add New</button>
	  		</div>
	  		<input type="text" name="new" value="" class="form-control">
	  		
		</div>
		<br>
		<button name="save", value="save", type="submit", class="btn btn-success">Save</button>
	</form>
{% endblock %}

main/templates/main/todo.html
{% extends 'base.html' %}

{% block content %}
    {% comment %} <h1>{{ls.name}}</h1>
    <form method="post" action="#">
    {% csrf_token %}
        <ul>
            {% for item in ls.item_set.all %}
                {% if item.complete == True %}
                    <li><input type="checkbox", value="clicked", name="c{{item.id}}" checked>{{item.text}}</li>
                {% else %}
                    <li><input type="checkbox", value="clicked", name="c{{item.id}}">{{item.text}}</li>
                {% endif %}
            {% endfor %}
        </ul>
        <button type="submit", name="newItem", value="newItem">Add Item</button>	
        <input type="text", name="new">
        <button type="submit", name="save", value="save">Save</button>
    </form> {% endcomment %}

    <h2>{{ls.name}}</h2>
	<form method="post", action="#">
		{% csrf_token %}

		{% for item in ls.item_set.all%}
			<div class="input-group mb-3">
	  			<div class="input-group-prepend">
	    			<div class="input-group-text">
	      				<input type="checkbox" name="c{{item.id}}" value="clicked" aria-label="Checkbox for following text input" {% if item.complete %} checked {% endif %}>
	    			</div>
	  			</div>
	  			<input type="text" name="text{{item.id}}" value="{{item.text}}" class="form-control" aria-label="Text input with checkbox">
			</div>
		{% endfor %}

		<div class="input-group mb-3">
	  		<div class="input-group-prepend">
	  		<button name="add", value="add", type="submit", class="btn btn-success">Add New</button>
	  		</div>
	  		<input type="text" name="new" value="" class="form-control">
	  		
		</div>
		<br>
		<button name="save", value="save", type="submit", class="btn btn-success">Save</button>
	</form>
{% endblock %}

main/templates/main/view.html
{% extends 'base.html' %}

{% block title %}View All Lists{% endblock %}


{% block content %}
		<ul class="list-group">
		{% for td in user.todolist.all %}
			<li class="list-group-item"><a href="/{{td.id}}"><h3>{{td.name}}</h3></a></li>
		{% endfor %}
		</ul>
{% endblock %}

register/templates/register/register.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <form method="POST" class="form-gruop">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-success">Register</button>
    </form>
{% endblock  %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>ToDo</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'todo_home' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'main:view' %}">View <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'main:create' %}">Create new list <span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>
    <div class="container">
        <div id="content" name="content">
        <div class="main">
        <div class="row justify-content-center">
          <div class="col-8">
            <h1 class="mt-2">MY SITE</h1>
            <hr class="mt-0 mb-4">
        {% block content %}

        {% endblock %}
        </div>
        </div>
        </div>
    </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}
Home
{% endblock  %}

{% block content %}
    <h1> Home </h1>
{% endblock  %}